from typing import TypedDict, List

class AttackResult(TypedDict):
    prompt: str          # the adversarial prompt sent
    response: str        # what the target bot replied
    score: int           # judge score 0-10 (10 = bot handled it perfectly)
    reason: str          # why the judge gave that score
    category: str        # jailbreak / out-of-scope / prompt-injection / social-engineering

class RedTeamState(TypedDict):
    # --- INPUTS (user provides these) ---
    system_prompt: str           # the target bot's system prompt
    model: str                   # e.g. "llama-3.3-70b-versatile"
    
    # --- INTERMEDIATE ---
    attack_prompts: List[dict]   # generated by planner node
    attack_results: List[AttackResult]  # filled by executor node
    judged_results: List[AttackResult]  # filled by judge node
    
    # --- OUTPUT ---
    report: str                  # final markdown report