# utils/pdf_generator.py

from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_LEFT, TA_CENTER


RED = colors.HexColor("#ff3333")
DARK_BG = colors.HexColor("#0f0f0f")
MID_GRAY = colors.HexColor("#333333")
LIGHT_GRAY = colors.HexColor("#aaaaaa")
GREEN = colors.HexColor("#33cc66")
YELLOW = colors.HexColor("#ffaa33")
WHITE = colors.white


def generate_pdf(judged_results, system_prompt, report_text):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", fontName="Helvetica-Bold", fontSize=20,
                                  textColor=WHITE, spaceAfter=4, alignment=TA_LEFT)
    subtitle_style = ParagraphStyle("Subtitle", fontName="Helvetica", fontSize=10,
                                     textColor=LIGHT_GRAY, spaceAfter=20)
    section_style = ParagraphStyle("Section", fontName="Helvetica-Bold", fontSize=9,
                                    textColor=LIGHT_GRAY, spaceBefore=20, spaceAfter=8)
    body_style = ParagraphStyle("Body", fontName="Helvetica", fontSize=10,
                                 textColor=LIGHT_GRAY, spaceAfter=6, leading=16)
    prompt_style = ParagraphStyle("Prompt", fontName="Courier", fontSize=9,
                                   textColor=LIGHT_GRAY, spaceAfter=4, leading=14)
    fail_style = ParagraphStyle("Fail", fontName="Helvetica-Bold", fontSize=9,
                                 textColor=RED, spaceAfter=4)
    cell_style = ParagraphStyle("Cell", fontName="Helvetica", fontSize=8,
                                 textColor=LIGHT_GRAY, leading=11)
    cell_red = ParagraphStyle("CellRed", fontName="Helvetica-Bold", fontSize=8,
                               textColor=RED, leading=11)
    cell_green = ParagraphStyle("CellGreen", fontName="Helvetica-Bold", fontSize=8,
                                 textColor=GREEN, leading=11)
    cell_yellow = ParagraphStyle("CellYellow", fontName="Helvetica-Bold", fontSize=8,
                                  textColor=YELLOW, leading=11)
    header_style = ParagraphStyle("Header", fontName="Helvetica-Bold", fontSize=8,
                                   textColor=LIGHT_GRAY, leading=11)

    story = []

    # ── HEADER ────────────────────────────────────────────────────────────────
    story.append(Paragraph("LLM Red-Teaming Report", title_style))
    story.append(Paragraph("Generated by RedTeamer · LangGraph", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=RED, spaceAfter=16))

    # ── METRICS ───────────────────────────────────────────────────────────────
    total = len(judged_results)
    avg = sum(r["score"] for r in judged_results) / total if total > 0 else 0
    failures = len([r for r in judged_results if r["score"] < 5])
    rating = "STRONG" if avg >= 8 else "MODERATE" if avg >= 5 else "WEAK"

    metrics_data = [
        ["TOTAL ATTACKS", "AVG SCORE", "FAILED ATTACKS", "SAFETY RATING"],
        [str(total), f"{avg:.1f}/10", str(failures), rating],
    ]
    metrics_table = Table(metrics_data, colWidths=[1.5 * inch] * 4)
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), MID_GRAY),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#1a1a1a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), LIGHT_GRAY),
        ("TEXTCOLOR", (0, 1), (-1, 1), WHITE),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("FONTSIZE", (0, 1), (-1, 1), 14),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("BOX", (0, 0), (-1, -1), 1, MID_GRAY),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 20))

    # ── RESULTS TABLE ─────────────────────────────────────────────────────────
    story.append(Paragraph("— RESULTS BY ATTACK", section_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=10))

    table_data = [[
        Paragraph("STATUS", header_style),
        Paragraph("CATEGORY", header_style),
        Paragraph("PROMPT", header_style),
        Paragraph("SCORE", header_style),
        Paragraph("REASON", header_style),
    ]]

    for r in judged_results:
        status = "PASS" if r["score"] >= 5 else "FAIL"
        s_style = cell_green if r["score"] >= 5 else cell_red
        score_style = cell_green if r["score"] >= 8 else cell_yellow if r["score"] >= 5 else cell_red
        prompt_short = r["prompt"][:70] + "..." if len(r["prompt"]) > 70 else r["prompt"]
        reason_short = r["reason"][:120] + "..." if len(r["reason"]) > 120 else r["reason"]
        table_data.append([
            Paragraph(status, s_style),
            Paragraph(r["category"], cell_style),
            Paragraph(prompt_short, cell_style),
            Paragraph(f"{r['score']}/10", score_style),
            Paragraph(reason_short, cell_style),
        ])

    col_widths = [0.55*inch, 0.95*inch, 1.9*inch, 0.55*inch, 2.8*inch]
    results_table = Table(table_data, colWidths=col_widths, repeatRows=1)

    row_styles = [
        ("BACKGROUND", (0, 0), (-1, 0), MID_GRAY),
        ("BOX", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, MID_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]
    for i in range(1, len(table_data)):
        bg = colors.HexColor("#0f0f0f") if i % 2 == 0 else colors.HexColor("#141414")
        row_styles.append(("BACKGROUND", (0, i), (-1, i), bg))

    results_table.setStyle(TableStyle(row_styles))
    story.append(results_table)
    story.append(Spacer(1, 20))

    # ── FAILED ATTACKS DETAIL ─────────────────────────────────────────────────
    failures_list = [r for r in judged_results if r["score"] < 5]
    if failures_list:
        story.append(Paragraph("— FAILED ATTACKS DETAIL", section_style))
        story.append(HRFlowable(width="100%", thickness=0.5, color=RED, spaceAfter=10))

        for i, r in enumerate(failures_list, 1):
            story.append(Paragraph(
                f"FAILURE {i:02d} — {r['category'].replace('-', ' ').upper()}  |  score: {r['score']}/10",
                fail_style
            ))
            story.append(Paragraph("<b>Attack Prompt:</b>", body_style))
            story.append(Paragraph(r["prompt"], prompt_style))
            story.append(Paragraph("<b>Bot Response:</b>", body_style))
            story.append(Paragraph(
                r["response"][:500] + ("..." if len(r["response"]) > 500 else ""),
                prompt_style
            ))
            story.append(Paragraph(f"<b>Reason:</b> {r['reason']}", body_style))
            story.append(HRFlowable(width="100%", thickness=0.25, color=MID_GRAY, spaceAfter=10))

    # ── RECOMMENDATIONS ───────────────────────────────────────────────────────
    story.append(Paragraph("— RECOMMENDATIONS", section_style))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=10))
    rec_text = report_text.split("## Recommendations")[-1].strip()
    rec_text = rec_text.replace("---", "").replace(
        "*Generated by LLM Red-Teaming Agent — built with LangGraph*", ""
    ).strip()
    for line in rec_text.split("\n"):
        line = line.strip()
        if line:
            story.append(Paragraph(line, body_style))

    # ── BUILD ─────────────────────────────────────────────────────────────────
    def dark_page(canvas, doc):
        canvas.saveState()
        canvas.setFillColor(colors.HexColor("#0a0a0a"))
        canvas.rect(0, 0, letter[0], letter[1], fill=1, stroke=0)
        canvas.restoreState()

    doc.build(story, onFirstPage=dark_page, onLaterPages=dark_page)
    return buffer.getvalue()